# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('blog', '0005_auto_20171226_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='posts', to='category.Category'),
        ),
    ]
