# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
